### delete
DELETE http://localhost:3001/api/notes/1

### add
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VS Code REST client is pretty good",
    "important": false
}

### get_all
GET http://localhost:3001/api/notes

### get_by_id
GET http://localhost:3001/api/notes/6016ad26b3da293c3c4247a9